export const ERRORS = {
	NOT_GOVERNANCE: 'NotGovernance',
	NOT_GOVERNANCE_OR_EMERGENCY_ADMIN: 'NotGovernanceOrEmergencyAdmin',
	EMERGENCY_ADMIN_CANNOT_UNPAUSE: 'EmergencyAdminCannotUnpause',
	PAUSED: 'Paused',
	PUBLISHING_PAUSED: 'PublishingPaused',
	CANNOT_INIT_IMPL: 'CannotInitImplementation',
	INITIALIZED: 'Initialized',
	SIGNATURE_EXPIRED: 'SignatureExpired',
	ZERO_SPENDER: 'ZeroSpender',
	PRICE_ZERO: 'PriceZero',
	SIGNATURE_INVALID: 'SignatureInvalid',
	NOT_OWNER_OR_APPROVED: 'NotOwnerOrApproved',
	NOT_HUB: 'NotHub',
	PROFILE_HANDLE_TAKEN: 'HandleTaken',
	TOKEN_DOES_NOT_EXIST: 'TokenDoesNotExist',
	CALLER_NOT_WHITELSITED_MODULE: 'CallerNotWhitelistedModule',
	COLLECT_MODULE_NOT_WHITELISTED: 'CollectModuleNotWhitelisted',
	MARKET_MODULE_NOT_WHITELISTED: 'MarketModuleNotWhitelisted',
	CURRENCY_MODULE_NOT_WHITELISTED: 'CurrencyNotWhitelisted',
	PROFILE_CREATOR_NOT_WHITELISTED: 'ProfileCreatorNotWhitelisted',
	NOT_PROFILE_OWNER: 'NotProfileOwner',
	CURATION_DOES_NOT_EXIST: 'CurationDoesNotExist',
	PROFILE_HANDLE_TOKEN: 'HandleToken', 
	INVALID_HANDLE_LENGTH: 'HandleLengthInvalid',
	HANDLE_CONTAINS_INVALID_CHARACTERS: 'HandleContainsInvalidCharacters',
	HANDLE_FIRST_CHARACTER_INVALID: 'HandleFirstCharInvalid',
	BLOCK_NUMBER_INVALID: 'BlockNumberInvalid',
	INIT_PARAMS_INVALID: 'InitParamsInvalid',
	TRADE_EXPIRED: 'TRADEExpired',
	TRADE_NOT_ALLOWED: 'TradeNotAllowed',
	MINT_LIMIT_EXCEEDED: 'MintLimitExceeded',
	TRADE_INVALID: 'TradeInvalid',
	MODULE_DATA_MISMATCH: 'ModuleDataMismatch',
	TRADE_NOT_APPROVED: 'TradeNotApproved',
	ARRAY_MISMATCH: 'ArrayMismatch',
	CANNOT_TRADE_WITH_SELF: 'CannotTradeWithSelf',
	ERC721_NOT_OWN: 'ERC721: transfer of token that is not own',
	ERC721_TRANSFER_NOT_OWNER_OR_APPROVED: 'ERC721: transfer caller is not owner nor approved',
	ERC721_QUERY_FOR_NONEXISTENT_TOKEN: 'ERC721: owner query for nonexistent token',
	ERC20_TRANSFER_EXCEEDS_ALLOWANCE: 'ERC20: transfer amount exceeds allowance',
	ERC20_INSUFFICIENT_ALLOWANCE: 'ERC20: insufficient allowance',
	NO_SELECTOR:
		"Transaction reverted: function selector was not recognized and there's no fallback function",
	NO_REASON_ABI_DECODE:
		"Transaction reverted and Hardhat couldn't infer the reason. Please report this to help us improve Hardhat.",
};