#!/bin/bash

## Before running:
# This tool requires to have solc installed.
# Ensure that you have the binaries installed by pip3 in your path.
# Install: 
# - https://github.com/crytic/slither#how-to-install
# Usage:
# - https://github.com/crytic/slither/wiki/Usage

mkdir -p dist/reports

pip3 install --user slither-analyzer && \
yarn build && \

echo "Analyzing contracts..."
slither . \
    --hardhat-ignore-compile \
    --hardhat-artifacts-directory ./dist/contracts \
    --sarif - \
    --filter-paths "contracts/staking/utils/Cobbs.*|contracts/staking/utils/LibFixedMath.*|contracts/utils/MathUtils.*" \
    --exclude-dependencies \
    --exclude similar-names,naming-convention \
    --disable-color \
    &> dist/reports/analyzer-report.sarif && \
echo "Slither report generated at ./dist/reports/analyzer-report.sarif"
echo "Checking ERC compliance..."
slither-check-erc dist/flatten/BardsCurationToken.sol BardsCurationToken &> dist/reports/analyzer-report-erc.log
echo "Compliance report generated at ./dist/reports/analyzer-report-erc.log"

echo "Done!"